version: 2.1                                                                    
orbs:                                                                           
  node: circleci/node@1.1.6                                                     
jobs:                                                                           
  lint:                                                                         
    executor:                                                                   
      name: node/default                                                        
    steps:                                                                      
        - checkout                                                              
        - run: npm install eslint                                               
        - run: npm run lint                                                     
workflows:                                                                      
    build-and-test:                                                             
      jobs:                                                                     
        - lint 
